# Generated by Django 5.0.7 on 2024-07-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_last_login_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
